services:
  postgresDB:
    image: postgres
    environment:
      POSTGRES_DB: ${CHESSDB_NAME}
      POSTGRES_USER: ${CHESSDB_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-db:/var/lib/postgresql/data